# -*- coding: utf-8 -*-
"""library.py

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1fu4Hs8dviNUIOokp48zcK__qrTVCkTpC
"""

#[V00705004] [Tamya] [Hunter]

ASCII_LOWERCASE = "abcdefghijklmnopqrstuvwxyz"
ASCII_UPPERCASE = "ABCDEFGHIJKLMNOPQRSTUVWXYZ"
DECIMAL_DIGITS = "0123456789"

def is_alpha(word) -> bool:
    for char in word:
        if char not in ASCII_LOWERCASE and char not in ASCII_UPPERCASE:
            return False
    return True

def is_digit(s) -> bool:
    if not s:  # Handle empty string
        return False
    for char in s:
        if char not in DECIMAL_DIGITS:
            return False
    return True

def to_lower(s) -> str:
    result = ''
    for char in s:
        if char in ASCII_UPPERCASE:
            result += ASCII_LOWERCASE[ASCII_UPPERCASE.index(char)]
        else:
            result += char
    return result

def to_upper(s) -> str:
    result = ''
    for char in s:
        if char in ASCII_LOWERCASE:
            result += ASCII_UPPERCASE[ASCII_LOWERCASE.index(char)]
        else:
            result += char
    return result

def find_chr(s, char) -> int:
    if len(char) != 1:
        return -1
    for index in range(len(s)):
        if s[index] == char:
            return index
    return -1

def find_str(s, substr) -> int:
    substr_len = len(substr)
    for index in range(len(s) - substr_len + 1):
        if s[index:index + substr_len] == substr:
            return index
    return -1

def replace_chr(s, old, new) -> str:
    if len(old) != 1 or len(new) != 1:
        return s
    result = ''
    for char in s:
        if char == old:
            result += new
        else:
            result += char
    return result

def replace_str(s, old, new) -> str:
    if old == '':
        return new.join(s)
    index = find_str(s, old)
    if index == -1:
        return s
    result = ''
    while index != -1:
        result += s[:index] + new
        s = s[index + len(old):]
        index = find_str(s, old)
    return result + s